"""RAG layer: BM25 retrieval over the knowledge base + optional Claude generation.

Retrieval is dependency-free so the app works with no API key (extractive mode).
When ANTHROPIC_API_KEY (or an `ant auth login` profile) is available, answers are
generated by Claude grounded in the retrieved passages.
"""
import math
import os
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

KNOWLEDGE_DIR = Path(__file__).parent / "knowledge"

_STOPWORDS = frozenset(
    "a an and are as at be but by for from has have if in is it its of on or that the "
    "this to was were what when which who will with your you how why does do".split()
)


def _tokenize(text: str) -> list[str]:
    return [t for t in re.findall(r"[a-z0-9/+-]+", text.lower()) if t not in _STOPWORDS]


@dataclass
class Chunk:
    source: str      # knowledge file name
    heading: str     # section heading
    text: str        # section body (includes heading line)
    tokens: list[str]


def _load_chunks() -> list[Chunk]:
    """Split each knowledge file into one chunk per '##' section."""
    chunks = []
    for path in sorted(KNOWLEDGE_DIR.glob("*.md")):
        raw = path.read_text()
        sections = re.split(r"\n(?=## )", raw)
        for sec in sections:
            sec = sec.strip()
            if not sec:
                continue
            first_line = sec.splitlines()[0].lstrip("# ").strip()
            chunks.append(Chunk(
                source=path.name,
                heading=first_line,
                text=sec,
                tokens=_tokenize(sec),
            ))
    return chunks


class BM25Index:
    def __init__(self, chunks: list[Chunk], k1: float = 1.5, b: float = 0.75):
        self.chunks = chunks
        self.k1, self.b = k1, b
        self.avgdl = sum(len(c.tokens) for c in chunks) / max(len(chunks), 1)
        self.df: dict[str, int] = {}
        for c in chunks:
            for term in set(c.tokens):
                self.df[term] = self.df.get(term, 0) + 1
        self.n = len(chunks)

    def _idf(self, term: str) -> float:
        df = self.df.get(term, 0)
        return math.log((self.n - df + 0.5) / (df + 0.5) + 1)

    def search(self, query: str, k: int = 4) -> list[tuple[Chunk, float]]:
        q_terms = _tokenize(query)
        scored = []
        for chunk in self.chunks:
            dl = len(chunk.tokens)
            score = 0.0
            for term in q_terms:
                tf = chunk.tokens.count(term)
                if tf == 0:
                    continue
                score += self._idf(term) * (tf * (self.k1 + 1)) / (
                    tf + self.k1 * (1 - self.b + self.b * dl / self.avgdl)
                )
            if score > 0:
                scored.append((chunk, score))
        scored.sort(key=lambda x: x[1], reverse=True)
        return scored[:k]


@lru_cache(maxsize=1)
def get_index() -> BM25Index:
    return BM25Index(_load_chunks())


def retrieve(query: str, k: int = 4) -> list[dict]:
    return [
        {"source": c.source, "heading": c.heading, "text": c.text, "score": round(s, 3)}
        for c, s in get_index().search(query, k=k)
    ]


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """You are the assistant inside the Portfolio Decision Tool, an
educational backtesting app. Answer questions about finance concepts, asset classes,
allocation strategies, market history, and how this tool computes its metrics.

Ground your answers in the reference passages provided. If the passages don't cover
the question, say so and answer briefly from general knowledge, flagging that it's
outside the tool's knowledge base.

Rules:
- You are not a licensed financial advisor. Never give personalized investment
  advice, recommendations to buy or sell, or predictions about future returns. If
  asked, explain the relevant concepts and suggest consulting a licensed advisor.
- Keep answers concise: a few sentences to two short paragraphs.
- Cite which section you drew from when it's load-bearing, e.g. (metrics.md)."""


def _claude_available() -> bool:
    if os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN"):
        return True
    # An `ant auth login` profile also works; the SDK resolves it lazily.
    cfg = Path.home() / ".config" / "anthropic"
    return cfg.exists() and any(cfg.glob("credentials/*.json"))


def answer(query: str, history: list[dict] | None = None) -> dict:
    """Answer a question. Returns {answer, sources, mode}.

    mode is "claude" when generated by the model, "extractive" when the app has no
    API credentials and returns the retrieved passages directly.
    """
    passages = retrieve(query, k=4)
    sources = [{"source": p["source"], "heading": p["heading"]} for p in passages]

    if _claude_available():
        try:
            return {
                "answer": _generate(query, passages, history or []),
                "sources": sources,
                "mode": "claude",
            }
        except Exception:
            pass  # fall through to extractive

    if not passages:
        return {
            "answer": "I couldn't find anything relevant in the knowledge base. "
                      "Try asking about the supported tickers, metrics like Sharpe or "
                      "max drawdown, or strategies like the 60/40 portfolio.",
            "sources": [],
            "mode": "extractive",
        }
    top = passages[0]
    return {
        "answer": f"From the knowledge base ({top['source']} — {top['heading']}):\n\n"
                  f"{_body(top['text'])}",
        "sources": sources,
        "mode": "extractive",
    }


def _body(section: str) -> str:
    lines = section.splitlines()
    return "\n".join(lines[1:]).strip() if len(lines) > 1 else section


def _generate(query: str, passages: list[dict], history: list[dict]) -> str:
    import anthropic

    context = "\n\n---\n\n".join(
        f"[{p['source']} — {p['heading']}]\n{p['text']}" for p in passages
    )
    messages = []
    for turn in history[-6:]:  # keep the last 3 exchanges
        if turn.get("role") in ("user", "assistant") and turn.get("content"):
            messages.append({"role": turn["role"], "content": turn["content"]})
    messages.append({
        "role": "user",
        "content": f"Reference passages:\n\n{context}\n\nQuestion: {query}",
    })

    client = anthropic.Anthropic()
    response = client.beta.messages.create(
        model="claude-opus-5",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        betas=["server-side-fallback-2026-07-01"],
        fallbacks="default",
        messages=messages,
    )
    if response.stop_reason == "refusal":
        return ("I can't help with that request. Try asking about portfolio metrics, "
                "asset classes, or allocation strategies.")
    return "".join(b.text for b in response.content if b.type == "text").strip()
